language: ruby
script: "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx
notifications:
  email:
    - pnascimento@gmail.com
    - oriekenjr@gmail.com